# Generated by Django 4.1.3 on 2023-02-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datecompra',
            field=models.TextField(max_length=100, verbose_name='Datecompra'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lote',
            field=models.TextField(max_length=100, verbose_name='Lote'),
        ),
    ]
